{{- define "platform.deployment" -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "platform.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "platform.labels" . | nindent 4 }}
    {{- range $k, $v := .Values.commonLabels }}
    {{ $k }}: {{ $v | quote }}
    {{- end }}
    {{- range $k, $v := .Values.labels }}
    {{ $k }}: {{ $v | quote }}
    {{- end }}
  {{- if or .Values.commonAnnotations .Values.annotations }}
  annotations:
    {{- range $k, $v := .Values.commonAnnotations }}
    {{ $k }}: {{ $v | quote }}
    {{- end }}
    {{- range $k, $v := .Values.annotations }}
    {{ $k }}: {{ $v | quote }}
    {{- end }}
  {{- end }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit }}
  selector:
    matchLabels:
      {{- include "platform.selectorLabels" . | nindent 6 }}
  {{- if .Values.updateStrategy }}
  strategy: {{- toYaml .Values.updateStrategy | nindent 4 }}
  {{- end }}
  template:
    {{- include "platform.podTemplateSpec" . | nindent 4 }}
{{- end }}

