{{- if .Values.configMap.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "platform.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "platform.labels" . | nindent 4 }}
    {{- range $k, $v := .Values.commonLabels }}
    {{ $k }}: {{ $v | quote }}
    {{- end }}
    {{- range $k, $v := .Values.configMap.labels }}
    {{ $k }}: {{ $v | quote }}
    {{- end }}
  {{- $annotations := dict -}}
  {{- range $k, $v := .Values.commonAnnotations }}
    {{- $_ := set $annotations $k $v -}}
  {{- end }}
  {{- range $k, $v := .Values.configMap.annotations }}
    {{- $_ := set $annotations $k $v -}}
  {{- end }}
  {{- if gt (len $annotations) 0 }}
  annotations:
    {{- range $k, $v := $annotations }}
    {{ $k }}: {{ $v | quote }}
    {{- end }}
  {{- end }}
data:
  {{- range $key, $value := .Values.configMap.data }}
  {{ $key }}: |
{{- if kindIs "string" $value }}
{{ $value | indent 4 }}
{{- else }}
{{ toYaml $value | indent 4 }}
{{- end }}
  {{- end }}
{{- end }}
